name: DeepSeek Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: DeepSeek Coder
    provider: deepseek
    model: deepseek-coder
    apiKey: "sk-a2f4cdd586dc48efb6613183a073a735"

  - name: DeepSeek Chat
    provider: deepseek
    model: deepseek-chat
    apiKey: "sk-a2f4cdd586dc48efb6613183a073a735"

  - name: DeepSeek Reasoner
    provider: deepseek
    model: deepseek-reasoner
    apiKey: "sk-a2f4cdd586dc48efb6613183a073a735"